### ISSUE TITLE
Buttons to increase/decrease the timestamp slider

### ISSUE THREAD

**Issue by charc-m3** [jmerle/imc-prosperity-2-visualizer#2]
Can you please add two buttons to increase/decrease the timestamp slider by 1 time step? It is quite difficult to move the slider accurately when the number of time steps gets large.

**Comment by jmerle** [comment]
You can use the keyboard to go step-by-step. Click on the slider to focus it, then use the up/down arrow keys to navigate timestamp-by-timestamp.

**Comment by charc-m3** [comment]
Oh cool! Thank you for pointing that out 😀.
